// <auto-generated />
using jmbde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace jmbde.Migrations
{
    [DbContext(typeof(JMBDEContext))]
    [Migration("20170829193815_Initial_Create")]
    partial class Initial_Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("jmbde.Models.Computer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("jmbde.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("BusinessMail")
                        .HasMaxLength(40);

                    b.Property<string>("ChipCard")
                        .HasMaxLength(20);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<int?>("CompanyId");

                    b.Property<bool?>("DataCare");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("EmployeeNO")
                        .IsRequired();

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Mail")
                        .HasMaxLength(40);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(20);

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Notes");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.Property<int?>("PlaceId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.Property<int?>("WorkfunctionId");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("jmbde.Models.Mobile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("jmbde.Models.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("jmbde.Models.Computer", b =>
                {
                    b.HasOne("jmbde.Models.Employee", "Employee")
                        .WithMany("Computers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("jmbde.Models.Mobile", b =>
                {
                    b.HasOne("jmbde.Models.Employee", "Employee")
                        .WithOne("Mobile")
                        .HasForeignKey("jmbde.Models.Mobile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("jmbde.Models.Phone", b =>
                {
                    b.HasOne("jmbde.Models.Employee", "Employee")
                        .WithOne("Phone")
                        .HasForeignKey("jmbde.Models.Phone", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
