// <auto-generated />
using jmbde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace jmbde.Migrations
{
    [DbContext(typeof(JMBDEContext))]
    [Migration("20180227205927_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("jmbde.Models.Computer", b =>
                {
                    b.Property<long>("ComputerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Active");

                    b.Property<long?>("ComputerSoftwareId");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("EmployeeId");

                    b.Property<long?>("InventoryId");

                    b.Property<string>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<long?>("Memory");

                    b.Property<string>("Network");

                    b.Property<string>("NetworkIpAddress");

                    b.Property<string>("NetworkName");

                    b.Property<long?>("OsId");

                    b.Property<long?>("PlaceId");

                    b.Property<long?>("PrinterId");

                    b.Property<long?>("ProcessorId");

                    b.Property<string>("Replace");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("ServiceNumber");

                    b.Property<string>("ServiceTag");

                    b.HasKey("ComputerId");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("jmbde.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Active");

                    b.Property<string>("Address");

                    b.Property<string>("BirthDay");

                    b.Property<string>("BusinessMailAddress");

                    b.Property<long?>("ChipCardId");

                    b.Property<long?>("ComputerId");

                    b.Property<string>("DataCare");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("EmployeeAccountId");

                    b.Property<long?>("EmployeeDocumentId");

                    b.Property<long?>("EmployeeNr");

                    b.Property<string>("EndDate");

                    b.Property<long?>("FaxId");

                    b.Property<string>("FirstName");

                    b.Property<long?>("FunctionId");

                    b.Property<long?>("Gender");

                    b.Property<string>("HireDate");

                    b.Property<string>("HomeMailAddress");

                    b.Property<string>("HomeMobile");

                    b.Property<string>("HomePhone");

                    b.Property<string>("LastName");

                    b.Property<string>("LastUpdate");

                    b.Property<long?>("MobileId");

                    b.Property<string>("Notes");

                    b.Property<long?>("PhoneId");

                    b.Property<byte[]>("Photo");

                    b.Property<long?>("PrinterId");

                    b.Property<long?>("TitleId");

                    b.Property<long?>("ZipCityId");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("jmbde.Models.Mobile", b =>
                {
                    b.Property<long>("MobileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Active");

                    b.Property<string>("CardNumber");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("EmployeeId");

                    b.Property<long?>("InventoryId");

                    b.Property<string>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Number");

                    b.Property<string>("Pin");

                    b.Property<long?>("PlaceId");

                    b.Property<string>("Replace");

                    b.Property<string>("SerialNumber");

                    b.HasKey("MobileId");

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("jmbde.Models.Phone", b =>
                {
                    b.Property<long>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Active");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("EmployeeId");

                    b.Property<long?>("InventoryId");

                    b.Property<string>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Number");

                    b.Property<string>("Pin");

                    b.Property<long?>("PlaceId");

                    b.Property<string>("Replace");

                    b.Property<string>("SerialNumber");

                    b.HasKey("PhoneId");

                    b.ToTable("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
