---
version: 0.5.{build}
max_jobs: 1
image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

configuration:
  - Release
  # - Debug

platform:
  # Disable x86 builds since we only get one concurrent build on AppVeyor and x86
  # failures will be caught by Jenkins.
  # - x86
  # - x64

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*
    - LICENSE
    - README
    - CHANGELOG
    - COPYING

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
nuget:
  disable_publish_on_pr: true

environment:
  my_secret:
    secure: NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  Appveyor: true

for:
  ########## macOS SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: macOS

    clone_folder: /Users/appveyor/projects/jmbde

    # TODO: Activate by available LTS Version 3.1.100
    dotnet_csproj:
      patch: true
      file: '**/*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    build_script:
      - dotnet --info
      - dotnet build ./jmbde.sln -c Release

      #after_build:
      - dotnet publish ./jmbde.sln -c Release -o ./artifacts

      #test_script:
      - dotnet test ./tests/jmbde.Tests/jmbde.Tests.csproj

  ########## END macOS SPECIFIC CONFIGURATION ##########

  ########## UBUNTU SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: ubuntu

    clone_folder: /home/appveyor/projects/jmbde

    # TODO: Activate by available LTS Version 3.1.100
    dotnet_csproj:
      patch: true
      file: '**/*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    build_script:
      - dotnet --info
      - dotnet build ./jmbde.sln -c Release

    after_build:
      - dotnet publish ./jmbde.sln -c Release -o ./artifacts

    test_script:
      - dotnet test ./tests/jmbde.Tests/jmbde.Tests.csproj

  ########## END UBUNTU SPECIFIC CONFIGURATION ##########
  ########## WINDOWS SPECIFIC CONFIGURATION ##########
  - matrix:
      only:
        - image: Visual Studio 2019
      fast_finish: false # set this flag to true to immediately finish build once one of the jobs fails.

    cache:
      - C:\Users\appveyor\clcache -> .appveyor.yml, build_msvc\**, **\Makefile.am,
        **\*.vcxproj.in

    init:
      - git config --global core.autocrlf input
      # Uncomment the following line to show RDP info at beginning of job
      #    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      - call set ENVIRONMENT_NAME=%%ENVIRONMENT_NAME:PLATFORM=%platform%%%
      - call set ENVIRONMENT_NAME=%%ENVIRONMENT_NAME:CONFIGURATION=%configuration%%%
      - ps: $ENV:PLATFORM="x64"
      - ps:
          $ENV:VCVARSALL="C:\Program Files (x86)\Microsoft Visual
          Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat"

    clone_folder: c:\projects\jmbde

    install:
      # Windows
      - cinst opencover.portable
      - cinst codecov
      - nuget install secure-file -ExcludeVersion

    before_build:
      - call "C:\Program Files (x86)\Microsoft Visual
        Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
      - cmd: chdir %APPVEYOR_BUILD_FOLDER%
      - appveyor-retry dotnet restore -v Minimal

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'

    build_script:
      - ps: dotnet --info
      - ps: dotnet build .\jmbde.sln -c Release

    after_build:
      - ps: dotnet publish .\jmbde.sln -c Release -o .\artifacts

    test_script:
      - ps: dotnet test .\tests\jmbde.Tests\jmbde.Tests.csproj

    artifacts:
      - path: artifacts\**\*.*
        name: ReleaseArtifacts

    deploy: off
    # master deployment to release
    # - provider: NuGet
    #   release: $(APPVEYOR_REPO_TAG_NAME)
    #   api_key:
    #     secure: jNtt/O0YdM+cKFiPbqv5EXIgbXlvGzXR45WLJdEWdhIwKTUCoGr44lmUkVY9xigd
    #   artifact: cReleaseArtifacts
    #   draft: true
    #   on:
    #     appveyor_repo_tag: true
    #     push_release: true
    #
    # - provider: GitHub
    #   release: $(APPVEYOR_REPO_TAG_NAME)
    #   auth_token:
    #     secure: dgHvp6cRuN111wnt2rANR25qfklalE+m06hxhy7XbFRkoGjW46h9mu8wxqsaTPHj
    #   artifact: ReleaseArtifacts
    #   draft: true
    #   on:
    #     appveyor_repo_tag: true
    #     push_release: true

    on_finish:
    # Uncomment the following line if you don't want the build VM to be destroyed
    # and be able to RDP on it until a special “lock” file on VM desktop is deleted
    # The RDP session is limited by overall build time (60 min).
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    ########## END WINDOWS SPECIFIC CONFIGURATION ##########

on_success:
  - echo "*** SUCCESS ***"

on_failure:
  - echo "*** FAILURE ***"

on_finish:
  - echo "*** DONE ***"
