version: '3'
services:
  web:
    build: .
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: 'microsoft/mssql-server-linux'
    environment:
      SA_PASSWORD: 'Your_password123' #NO_CHECK
      # checkov:skip=CKV_SECRET_6: ADD REASON
      ACCEPT_EULA: 'Y'
