// <auto-generated />
using jmbde.Data;
using jmbde.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace jmbde.Migrations
{
    [DbContext(typeof(JMBDEContext))]
    [Migration("20180330171238_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("jmbde.Models.ChipCard", b =>
                {
                    b.Property<long>("ChipCardId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<bool>("Locked");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("ChipCardId");

                    b.ToTable("ChipCard");
                });

            modelBuilder.Entity("jmbde.Models.ChipCardDoor", b =>
                {
                    b.Property<long>("ChipCardDoorId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ChipCardId");

                    b.Property<long?>("ChipCardProfileId");

                    b.Property<long?>("DepartmentId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<long?>("PlaceId");

                    b.HasKey("ChipCardDoorId");

                    b.HasIndex("ChipCardId");

                    b.HasIndex("ChipCardProfileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PlaceId");

                    b.ToTable("ChipCardDoor");
                });

            modelBuilder.Entity("jmbde.Models.ChipCardProfile", b =>
                {
                    b.Property<long>("ChipCardProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ChipCardId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("ChipCardProfileId");

                    b.HasIndex("ChipCardId");

                    b.ToTable("ChipCardProfile");
                });

            modelBuilder.Entity("jmbde.Models.CityName", b =>
                {
                    b.Property<long>("CityNameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CityNameId");

                    b.ToTable("CityName");
                });

            modelBuilder.Entity("jmbde.Models.Company", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<long?>("EmployeeId");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("MailAddress")
                        .HasMaxLength(50);

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name2")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.Property<long?>("ZipCodeId");

                    b.HasKey("CompanyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("jmbde.Models.Computer", b =>
                {
                    b.Property<long>("ComputerId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("EmployeeId");

                    b.Property<long?>("InventoryId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<long?>("Memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Network")
                        .HasMaxLength(50);

                    b.Property<string>("NetworkIpAddress")
                        .HasMaxLength(50);

                    b.Property<long?>("OSSoftwareId");

                    b.Property<long?>("PlaceId");

                    b.Property<long?>("PrinterId");

                    b.Property<long?>("ProcessorId");

                    b.Property<bool>("Replace");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceTag")
                        .HasMaxLength(20);

                    b.HasKey("ComputerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OSSoftwareId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.HasIndex("ProcessorId");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("jmbde.Models.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("Priority");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("jmbde.Models.DeviceName", b =>
                {
                    b.Property<long>("DeviceNameId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DeviceNameId");

                    b.ToTable("DeviceName");
                });

            modelBuilder.Entity("jmbde.Models.DeviceType", b =>
                {
                    b.Property<long>("DeviceTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DeviceTypeId");

                    b.ToTable("DeviceType");
                });

            modelBuilder.Entity("jmbde.Models.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("DocumentData");

                    b.Property<long?>("EmployeeId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("DocumentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("jmbde.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("BirthDay");

                    b.Property<string>("BusinessMailAddress")
                        .HasMaxLength(50);

                    b.Property<long?>("ChipCardDoorId");

                    b.Property<long?>("ChipCardId");

                    b.Property<long?>("ChipCardProfileId");

                    b.Property<bool>("DataCare");

                    b.Property<long?>("DepartmentId");

                    b.Property<string>("EmployeeIdent");

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("FaxId");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<int>("Gender");

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("HomeMailAddress")
                        .HasMaxLength(50);

                    b.Property<string>("HomeMobile")
                        .HasMaxLength(50);

                    b.Property<string>("HomePhone")
                        .HasMaxLength(50);

                    b.Property<long?>("JobTitleId");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("MobileId");

                    b.Property<string>("Notes");

                    b.Property<long?>("PhoneId");

                    b.Property<byte[]>("Photo");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("ZipCodeId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ChipCardDoorId");

                    b.HasIndex("ChipCardId");

                    b.HasIndex("ChipCardProfileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FaxId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("MobileId")
                        .IsUnique();

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.HasIndex("ZipCodeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("jmbde.Models.Fax", b =>
                {
                    b.Property<long>("FaxId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("InventoryId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasMaxLength(10);

                    b.Property<long?>("PlaceId");

                    b.Property<bool>("Replace");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20);

                    b.HasKey("FaxId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Fax");
                });

            modelBuilder.Entity("jmbde.Models.Function", b =>
                {
                    b.Property<long>("FunctionId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EmployeeId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long?>("Priority");

                    b.HasKey("FunctionId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("jmbde.Models.Inventory", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("jmbde.Models.JobTitle", b =>
                {
                    b.Property<long>("JobTitleId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FromDate");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("JobTitleId");

                    b.ToTable("JobTitle");
                });

            modelBuilder.Entity("jmbde.Models.Manufacturer", b =>
                {
                    b.Property<long>("ManufacturerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50);

                    b.Property<string>("HotlineNumber")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("MailAddress")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name2")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.Property<string>("Street22")
                        .HasMaxLength(50);

                    b.Property<string>("Supporter")
                        .HasMaxLength(50);

                    b.Property<long?>("ZipCodeId");

                    b.HasKey("ManufacturerId");

                    b.HasIndex("ZipCodeId");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("jmbde.Models.Mobile", b =>
                {
                    b.Property<long>("MobileId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(30);

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("InventoryId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasMaxLength(10);

                    b.Property<long?>("PlaceId");

                    b.Property<bool>("Replace");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20);

                    b.HasKey("MobileId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("jmbde.Models.Phone", b =>
                {
                    b.Property<long>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("InventoryId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasMaxLength(10);

                    b.Property<long?>("PlaceId");

                    b.Property<bool>("Replace");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20);

                    b.HasKey("PhoneId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("jmbde.Models.Place", b =>
                {
                    b.Property<long>("PlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desk")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PlaceId");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("jmbde.Models.Printer", b =>
                {
                    b.Property<long>("PrinterId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<bool>("Color");

                    b.Property<long?>("DepartmentId");

                    b.Property<long?>("DeviceNameId");

                    b.Property<long?>("DeviceTypeId");

                    b.Property<long?>("EmployeeId");

                    b.Property<long?>("InventoryId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<long?>("ManufacturerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Network")
                        .HasMaxLength(50);

                    b.Property<string>("NetworkIpAddress")
                        .HasMaxLength(50);

                    b.Property<int>("PaperSize");

                    b.Property<long?>("PlaceId");

                    b.Property<bool>("Replace");

                    b.Property<string>("Resources");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceTag")
                        .HasMaxLength(20);

                    b.HasKey("PrinterId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceNameId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Printer");
                });

            modelBuilder.Entity("jmbde.Models.Processor", b =>
                {
                    b.Property<long>("ProcessorId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("ClockRate");

                    b.Property<int>("Cores");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ProcessorId");

                    b.ToTable("Processor");
                });

            modelBuilder.Entity("jmbde.Models.Software", b =>
                {
                    b.Property<long>("SoftwareId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ComputerId");

                    b.Property<string>("Fix")
                        .HasMaxLength(25);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Revision")
                        .HasMaxLength(25);

                    b.Property<string>("Version")
                        .HasMaxLength(25);

                    b.HasKey("SoftwareId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("jmbde.Models.SystemAccount", b =>
                {
                    b.Property<int>("SystemAccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EmployeeId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<long?>("SystemDataId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SystemAccountId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SystemDataId");

                    b.ToTable("SystemAccount");
                });

            modelBuilder.Entity("jmbde.Models.SystemData", b =>
                {
                    b.Property<long>("SystemDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CompanyId");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<bool>("Local");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SystemDataId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SystemData");
                });

            modelBuilder.Entity("jmbde.Models.ZipCode", b =>
                {
                    b.Property<long>("ZipCodeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Country")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastUpdate");

                    b.HasKey("ZipCodeId");

                    b.ToTable("ZipCode");
                });

            modelBuilder.Entity("jmbde.Models.ChipCardDoor", b =>
                {
                    b.HasOne("jmbde.Models.ChipCard")
                        .WithMany("ChipCardDoor")
                        .HasForeignKey("ChipCardId");

                    b.HasOne("jmbde.Models.ChipCardProfile")
                        .WithMany("ChipCardDoor")
                        .HasForeignKey("ChipCardProfileId");

                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("jmbde.Models.ChipCardProfile", b =>
                {
                    b.HasOne("jmbde.Models.ChipCard")
                        .WithMany("ChipCardProfile")
                        .HasForeignKey("ChipCardId");
                });

            modelBuilder.Entity("jmbde.Models.Company", b =>
                {
                    b.HasOne("jmbde.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("jmbde.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeId");
                });

            modelBuilder.Entity("jmbde.Models.Computer", b =>
                {
                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameId");

                    b.HasOne("jmbde.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("jmbde.Models.Employee")
                        .WithMany("Computer")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("jmbde.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("jmbde.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("jmbde.Models.Software", "OS")
                        .WithMany()
                        .HasForeignKey("OSSoftwareId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");

                    b.HasOne("jmbde.Models.Printer", "Printer")
                        .WithOne("Computer")
                        .HasForeignKey("jmbde.Models.Computer", "PrinterId");

                    b.HasOne("jmbde.Models.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId");
                });

            modelBuilder.Entity("jmbde.Models.Document", b =>
                {
                    b.HasOne("jmbde.Models.Employee")
                        .WithMany("Document")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("jmbde.Models.Employee", b =>
                {
                    b.HasOne("jmbde.Models.ChipCardDoor")
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardDoorId");

                    b.HasOne("jmbde.Models.ChipCard", "ChipCard")
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardId");

                    b.HasOne("jmbde.Models.ChipCardProfile")
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardProfileId");

                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.Fax", "Fax")
                        .WithMany("Employee")
                        .HasForeignKey("FaxId");

                    b.HasOne("jmbde.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId");

                    b.HasOne("jmbde.Models.Mobile", "Mobile")
                        .WithOne("Employee")
                        .HasForeignKey("jmbde.Models.Employee", "MobileId");

                    b.HasOne("jmbde.Models.Phone", "Phone")
                        .WithOne("Employee")
                        .HasForeignKey("jmbde.Models.Employee", "PhoneId");

                    b.HasOne("jmbde.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeId");
                });

            modelBuilder.Entity("jmbde.Models.Fax", b =>
                {
                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany("Fax")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameId");

                    b.HasOne("jmbde.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("jmbde.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("jmbde.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("jmbde.Models.Function", b =>
                {
                    b.HasOne("jmbde.Models.Employee")
                        .WithMany("Function")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("jmbde.Models.Manufacturer", b =>
                {
                    b.HasOne("jmbde.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeId");
                });

            modelBuilder.Entity("jmbde.Models.Mobile", b =>
                {
                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameId");

                    b.HasOne("jmbde.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("jmbde.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("jmbde.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("jmbde.Models.Phone", b =>
                {
                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameId");

                    b.HasOne("jmbde.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("jmbde.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("jmbde.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("jmbde.Models.Printer", b =>
                {
                    b.HasOne("jmbde.Models.Department", "Department")
                        .WithMany("Printer")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("jmbde.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameId");

                    b.HasOne("jmbde.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");

                    b.HasOne("jmbde.Models.Employee", "Employee")
                        .WithMany("Printer")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("jmbde.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("jmbde.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("jmbde.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");
                });

            modelBuilder.Entity("jmbde.Models.Software", b =>
                {
                    b.HasOne("jmbde.Models.Computer")
                        .WithMany("Software")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("jmbde.Models.SystemAccount", b =>
                {
                    b.HasOne("jmbde.Models.Employee")
                        .WithMany("SystemAccount")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("jmbde.Models.SystemData", "SystemData")
                        .WithMany()
                        .HasForeignKey("SystemDataId");
                });

            modelBuilder.Entity("jmbde.Models.SystemData", b =>
                {
                    b.HasOne("jmbde.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
