// <auto-generated />
using System;
using JMuelbert.BDE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace jmbde.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191229091325_pgsl")]
    partial class pgsl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ChipCard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.ToTable("ChipCard");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ChipCardDoor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ChipCardID")
                        .HasColumnType("integer");

                    b.Property<int?>("ChipCardProfileID")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChipCardID");

                    b.HasIndex("ChipCardProfileID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("PlaceID");

                    b.ToTable("ChipCardDoor");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ChipCardProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ChipCardID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.HasIndex("ChipCardID");

                    b.ToTable("ChipCardProfile");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.CityName", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("CityName");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MailAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MobileNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name2")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ZipCodeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Computer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("integer");

                    b.Property<long?>("Memory")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Network")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NetworkIpAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("OSID")
                        .HasColumnType("integer");

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessorID")
                        .HasColumnType("integer");

                    b.Property<bool>("Replace")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceTag")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DeviceNameID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("OSID");

                    b.HasIndex("PlaceID");

                    b.HasIndex("ProcessorID");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.DeviceName", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("DeviceName");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.DeviceType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("DeviceType");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Document", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("DocumentData")
                        .HasColumnType("bytea");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BusinessMailAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ChipCardDoorID")
                        .HasColumnType("integer");

                    b.Property<int?>("ChipCardID")
                        .HasColumnType("integer");

                    b.Property<int?>("ChipCardProfileID")
                        .HasColumnType("integer");

                    b.Property<bool>("DataCare")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeIdent")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FaxID")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HomeMailAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HomeMobile")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HomePhone")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("JobTitleID")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MobileID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PersonID")
                        .HasColumnType("integer");

                    b.Property<string>("PersonIdent")
                        .HasColumnType("text");

                    b.Property<int?>("PhoneID")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ZipCodeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChipCardDoorID");

                    b.HasIndex("ChipCardID");

                    b.HasIndex("ChipCardProfileID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("FaxID");

                    b.HasIndex("JobTitleID");

                    b.HasIndex("MobileID");

                    b.HasIndex("PhoneID");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Fax", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.Property<bool>("Replace")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DeviceNameID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("PlaceID");

                    b.ToTable("Fax");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.JobTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("JobTitle");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FaxNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HotlineNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MailAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name2")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Street22")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Supporter")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ZipCodeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ZipCodeID");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Mobile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CardNumber")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.Property<bool>("Replace")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DeviceNameID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("PlaceID");

                    b.ToTable("Mobile");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pin")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.Property<bool>("Replace")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DeviceNameID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("PlaceID");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Desk")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Printer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Color")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ManufacturerID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Network")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NetworkIpAddress")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PaperSize")
                        .HasColumnType("integer");

                    b.Property<int?>("PlaceID")
                        .HasColumnType("integer");

                    b.Property<bool>("Replace")
                        .HasColumnType("boolean");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ServiceTag")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DeviceNameID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("PlaceID");

                    b.ToTable("Printer");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Processor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("ClockRate")
                        .HasColumnType("real");

                    b.Property<int>("Cores")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Processor");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Software", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ComputerID")
                        .HasColumnType("integer");

                    b.Property<string>("Fix")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Revision")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Version")
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.HasIndex("ComputerID");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.SystemAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("SystemDataID")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SystemDataID");

                    b.ToTable("SystemAccount");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.SystemData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Local")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("SystemData");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.WorkFunction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<long?>("Priority")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("WorkFunction");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ZipCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Country")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("ZipCode");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ChipCardDoor", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCard", null)
                        .WithMany("ChipCardDoor")
                        .HasForeignKey("ChipCardID");

                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCardProfile", null)
                        .WithMany("ChipCardDoor")
                        .HasForeignKey("ChipCardProfileID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.ChipCardProfile", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCard", null)
                        .WithMany("ChipCardProfile")
                        .HasForeignKey("ChipCardID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Company", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Computer", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", null)
                        .WithMany("Computer")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Software", "OS")
                        .WithMany()
                        .HasForeignKey("OSID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Document", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", null)
                        .WithMany("Document")
                        .HasForeignKey("EmployeeID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Employee", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCardDoor", null)
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardDoorID");

                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCard", "ChipCard")
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardID");

                    b.HasOne("JMuelbert.BDE.Data.Models.ChipCardProfile", null)
                        .WithMany("Employee")
                        .HasForeignKey("ChipCardProfileID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Fax", "Fax")
                        .WithMany("Employee")
                        .HasForeignKey("FaxID");

                    b.HasOne("JMuelbert.BDE.Data.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Mobile", "Mobile")
                        .WithMany()
                        .HasForeignKey("MobileID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneID");

                    b.HasOne("JMuelbert.BDE.Data.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Fax", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany("Fax")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Manufacturer", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ZipCodeID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Mobile", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Phone", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Printer", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Department", "Department")
                        .WithMany("Printer")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceName", "DeviceName")
                        .WithMany()
                        .HasForeignKey("DeviceNameID");

                    b.HasOne("JMuelbert.BDE.Data.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", "Employee")
                        .WithMany("Printer")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("JMuelbert.BDE.Data.Models.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.Software", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Computer", null)
                        .WithMany("Software")
                        .HasForeignKey("ComputerID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.SystemAccount", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", null)
                        .WithMany("SystemAccount")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("JMuelbert.BDE.Data.Models.SystemData", "SystemData")
                        .WithMany()
                        .HasForeignKey("SystemDataID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.SystemData", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("JMuelbert.BDE.Data.Models.WorkFunction", b =>
                {
                    b.HasOne("JMuelbert.BDE.Data.Models.Employee", null)
                        .WithMany("WorkFunction")
                        .HasForeignKey("EmployeeID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
