---
# SPDX-FileCopyrightText: Alex Page
#
# SPDX-License-Identifier: MIT

name: Move assigned pull requests into To do

on:
  pull_request:
    types: [assigned]
    branches:
      - "*"
    paths-ignore:
      - ".github/workflows/assigned-pulls-todo.yml"

permissions:
  contents: read

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest

    steps:
      - name: "🧰 Check out code"
        uses: actions/checkout@v3

      - name: Run Project Automation
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: test-connections
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
