---
# SPDX-FileCopyrightText: Alex Page
#
# SPDX-License-Identifier: MIT

name: Move assigned pull requests into To do

on:
  pull_request:
    types: [assigned]

permissions:
  contents: read

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: test-connections
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
