name: github pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Checkout Source code
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          #          ref: master

      - name: Checkout Source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: brew update-reset
        run: brew update-reset

      - name: brew update
        run: brew update

      - name: Install dependencies with homebrew
        run: |
          brew install graphviz doxygen
          brew install sphinx-doc
          brew install sphinx-sitemap
          brew install sphinx-rtd-theme
          brew install pkg-config
          brew install breathe
          brew ls | grep -wq freetype | brew install freetype
          brew ls | grep -wq python | brew install python

      - name: Build manual
        run: |
          ls $GITHUB_WORKSPACE/docs/manual
          cd $GITHUB_WORKSPACE/docs/manual
          make html
          cd $GITHUB_WORKSPACE/docs/manual/build/html
          touch .nojekyll

      - name: Deploy manual
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/manual/build/html # The folder the action should deploy.
